services:
  redis-sentinel-ap1:
    build:
      context: ../
      dockerfile: AP/Dockerfile
    container_name: redis-sentinel-ap1
    environment:
    - ASPNETCORE_ENVIRONMENT=RedisSentinel
    - ASPNETCORE_HTTP_PORTS=80
    - TZ=Asia/Taipei
    ports:
    - "7001:80"

  master:
    image: redis:6.2.19
    container_name: sentinel-master
    environment:
    - TZ=Asia/Taipei
    command: > #--appendonly yes 開啟 AOF
      redis-server --repl-diskless-sync yes --repl-diskless-load on-empty-db --replica-announce-ip 192.168.1.91 --replica-announce-port 6382
    volumes:
    - ./data/redis-master/data:/data
    ports:
    - "6382:6379"

  slave1:
    image: redis:6.2.19
    container_name: sentinel-slave1
    environment:
    - TZ=Asia/Taipei
    command: > #--appendonly yes 開啟 AOF
      redis-server --replicaof sentinel-master 6379  --repl-diskless-sync yes --repl-diskless-load on-empty-db --replica-announce-ip 192.168.1.91 --replica-announce-port 6383
    depends_on:
    - master
    volumes:
    - ./data/redis-slave1/data:/data
    ports:
    - "6383:6379"

  slave2:
    image: redis:6.2.19
    container_name: sentinel-slave2
    environment:
    - TZ=Asia/Taipei
    command: > #--appendonly yes 開啟 AOF
      redis-server --replicaof sentinel-master 6379  --repl-diskless-sync yes --repl-diskless-load on-empty-db --replica-announce-ip 192.168.1.91 --replica-announce-port 6384
    depends_on:
    - master
    volumes:
    - ./data/redis-slave2/data:/data
    ports:
    - "6384:6379"

  sentinel1:
    image: redis:6.2.19
    container_name: sentinel1
    ports:
    - 26379:26379
    environment:
    - TZ=Asia/Taipei
    command: redis-server /data/sentinel.conf --sentinel
    volumes:
    - ./sentinel1:/data
    depends_on:
    - slave2

  sentinel2:
    image: redis:6.2.19
    container_name: sentinel2
    ports:
    - 26380:26379
    environment:
    - TZ=Asia/Taipei
    command: >
      redis-server /data/sentinel.conf --sentinel
    volumes:
    - ./sentinel2:/data
    depends_on:
    - slave2

  sentinel3:
    image: redis:6.2.19
    container_name: sentinel3
    ports:
    - 26381:26379
    environment:
    - TZ=Asia/Taipei
    command: >
      redis-server /data/sentinel.conf --sentinel
    volumes:
    - ./sentinel3:/data
    depends_on:
    - slave2
