services:
  redis-sentinel-ap1:
    build:
      context: ../
      dockerfile: AP/Dockerfile
    container_name: redis-sentinel-ap1
    environment:
    - ASPNETCORE_HTTP_PORTS=80
    - TZ=Asia/Taipei
    ports:
    - "7001:80"

  master:
    image: redis:6.2.19
    container_name: sentinel-master
    command: > #--appendonly yes 開啟 AOF
      redis-server --repl-diskless-sync yes --repl-diskless-load on-empty-db
    volumes:
    - ./data/redis-master/data:/data
    ports:
    - "6382:6379"

  slave1:
    image: redis:6.2.19
    container_name: sentinel-slave1
    command: > #--appendonly yes 開啟 AOF
      redis-server --replicaof redis-master 6379 --repl-diskless-sync yes --repl-diskless-load on-empty-db
    depends_on:
    - master
    volumes:
    - ./data/redis-slave1/data:/data
    ports:
    - "6383:6379"

  slave2:
    image: redis:6.2.19
    container_name: sentinel-slave2
    command: > #--appendonly yes 開啟 AOF
      redis-server --replicaof redis-master 6379 --repl-diskless-sync yes --repl-diskless-load on-empty-db
    depends_on:
    - master
    volumes:
    - ./data/redis-slave2/data:/data
    ports:
    - "6384:6379"

  sentinel1:
    image: redis
    container_name: sentinel1
    ports:
    - 26379:26379
    command: >
      redis-server /data/sentinel.conf --sentinel
    volumes:
    - ./sentinel1:/data
    depends_on:
    - master

  sentinel2:
    image: redis
    container_name: sentinel2
    ports:
    - 26380:26379
    command: >
      redis-server /data/sentinel.conf --sentinel
    volumes:
    - ./sentinel2:/data
    depends_on:
    - master

  sentinel3:
    image: redis
    container_name: sentinel3
    ports:
    - 26381:26379
    command: >
      redis-server /data/sentinel.conf --sentinel
    volumes:
    - ./sentinel3:/data
    depends_on:
    - master
